stages:
  - build
  - deploy
job:
  stage: build
  before_script:
    - echo $(date +"%Y%m%d%H%M") 
    - apt update -y -qq && apt install -y -qq tesseract-ocr libtesseract-dev libleptonica-dev pkg-config
    - apt update -y -qq && apt install -y -qq rsync python3 python3-dev python3-pexpect python3-setuptools python3-wheel debhelper
    - export DEBIAN_FRONTEND=noninteractive && apt update -y -qq && apt install -y -qq python3-pip python3-django translate-toolkit python3-whoosh python3-pil git mercurial python3-django-compressor python3-django-crispy-forms python3-djangorestframework python3-dateutil python3-celery cython default-libmysqlclient-dev python3-psycopg2 python3-pymysql python3-mysqldb python3-requests-oauthlib python3-six python3-openid
    - echo "Asia/Shanghai" | tee /etc/timezone && dpkg-reconfigure --frontend noninteractive tzdata
    - pip3 install setuptools wheel social-auth-core social-auth-app-django django-crispy-forms whoosh django_compressor tesserocr psycopg2-binary mysqlclient pyuca
  script:
    - python3 setup.py bdist_wheel
  after_script:
    - echo $(date +"%Y%m%d%H%M")
  artifacts:
    paths:
      - build
      - dist
trigger_build:
  stage: deploy
  before_script:
    - echo $(date +"%Y%m%d%H%M") 
    - apt-get update -qq && apt-get install -y -qq curl
  script:
    - curl -X POST -F token=f45e690fdb1491d185e53e4b83cd70 -F "ref=master" http://47.102.156.191/api/v4/projects/6/trigger/pipeline
  after_script:
    - echo $(date +"%Y%m%d%H%M")